POST http://localhost:3333/trips
Content-Type: application/json

{
  "destination": "Xique Xique",
  "starts_at": "2024-07-10 18:00:00",
  "ends_at": "2024-07-16 18:00:00",
  "owner_name": "Bruno",
  "owner_email": "bruno@gmail.com",
  "emails_to_invite": ["diego.schell.f@gmail.com", "johndoe@acme.com"]
}

###
GET http://localhost:3333/listar