### GET PARTICIPANTS
GET http://localhost:3333/trips/396c6c65-b534-400f-8d25-1e3824a024ed/participants

### CREATE INVITE
POST http://localhost:3333/trips/396c6c65-b534-400f-8d25-1e3824a024ed/invites
Content-Type: application/json

{
  "email": "bia@gmail.com"
}

### GET PARTICIPANT
GET http://localhost:3333/participants/ea0b838e-c3a8-4454-8d2f-f9f13ecf9e52